services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fioulexpress
      POSTGRES_PASSWORD: fioulexpress
      POSTGRES_DB: fioulexpress
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
