# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "image_principale",
                    sorl.thumbnail.fields.ImageField(upload_to="actu"),
                ),
                ("contenu", ckeditor_uploader.fields.RichTextUploadingField()),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bloc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("contenu", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255, unique=True)),
                ("contenu", ckeditor_uploader.fields.RichTextUploadingField()),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
