# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0002_auto_20160725_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='url',
            field=models.SlugField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
