# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 06:19
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0003_actualite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
