# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0003_commande_livraison_ttc"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2016, 7, 31, 11, 29, 33, 908449),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commande",
            name="date_livraison",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 7, 31, 11, 29, 37, 324358)
            ),
            preserve_default=False,
        ),
    ]
