# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0004_auto_20160731_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="date_livraison",
            field=models.DateField(),
        ),
    ]
