# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0006_commande_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="email_admin",
            field=models.EmailField(default="admin@fioulexpress.fr", max_length=254),
            preserve_default=False,
        ),
    ]
