# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fioulexpress', '0007_config_email_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefioul',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typelivraison',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
