# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0008_auto_20160827_1057"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typefioul",
            options={
                "ordering": ["position"],
                "verbose_name": "type de fioul",
                "verbose_name_plural": "types de fiouls",
            },
        ),
        migrations.AlterModelOptions(
            name="typelivraison",
            options={
                "ordering": ["position"],
                "verbose_name": "type de livraison",
                "verbose_name_plural": "types de livraisons",
            },
        ),
    ]
