# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0009_auto_20160827_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="google_analytics_ua",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="config",
            name="meta_img",
            field=models.ImageField(blank=True, null=True, upload_to=b""),
        ),
        migrations.AddField(
            model_name="config",
            name="meta_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
