# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fioulexpress", "0011_distributeur_actif"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariffioul",
            options={"ordering": ["type_fioul__position"]},
        ),
        migrations.AddField(
            model_name="zone",
            name="adresse",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="code_postal",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="raison_sociale",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="siret",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
