# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fioulexpress', '0012_auto_20160910_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
