# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fioulexpress', '0013_zone_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='monetico_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
